"""
TRpsyDB — seed_classical_loci.py
Populates the database with well-established Tier 1 repeat expansion loci
and their associated studies. Run once after init_db().

Usage:
    python scripts/seed_classical_loci.py
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend.db.database import get_connection, init_db

# ── Classical Tier 1 loci ─────────────────────────────────────
# Sources: Hannan 2018, Paulson 2018, Orr & Zoghbi 2007,
#          STRchive, STRipy, OMIM, published literature

LOCI = [
    {
        "locus_id":         "chr4:3074876-3074940",
        "chrom":            "chr4",
        "start":            3074876,
        "end":              3074940,
        "motif":            "CAG",
        "motif_length":     3,
        "reference_copies": 17.0,
        "normal_max":       35,
        "pathogenic_min":   36,
        "gene_symbol":      "HTT",
        "ensembl_gene_id":  "ENSG00000197386",
        "gene_region":      "exon",
        "tss_distance":     428,
        "splice_distance":  0,
        "rexprt_score":     0.98,
        "pli":              0.97,
        "loeuf":            0.12,
        "gnomad_mean_copies": 18.2,
        "gnomad_sd_copies":   3.1,
        "gnomad_url":       "https://gnomad.broadinstitute.org/short-tandem-repeat/HTT",
        "in_schema":        0,
        "in_bipex":         0,
        "in_scz_gwas":      0,
        "in_bpd_gwas":      0,
        "in_asd_gwas":      0,
        "evidence_tier":    1,
        "n_studies_tested": 50,
        "n_studies_positive": 50,
        "replication_status": "replicated",
        "phenotypes":       "HD",
        "common_name":      "Huntington disease CAG repeat",
        "notes":            "The canonical trinucleotide repeat expansion disorder. CAG>36 repeats causes Huntington disease with full penetrance above 40 repeats. Anticipation occurs through paternal transmission. Protein: huntingtin.",
    },
    {
        "locus_id":         "chrX:147912051-147912110",
        "chrom":            "chrX",
        "start":            147912051,
        "end":              147912110,
        "motif":            "CGG",
        "motif_length":     3,
        "reference_copies": 30.0,
        "normal_max":       55,
        "pathogenic_min":   200,
        "gene_symbol":      "FMR1",
        "ensembl_gene_id":  "ENSG00000102081",
        "gene_region":      "5UTR",
        "tss_distance":     0,
        "splice_distance":  2100,
        "rexprt_score":     0.97,
        "pli":              0.96,
        "loeuf":            0.09,
        "gnomad_mean_copies": 30.1,
        "gnomad_sd_copies":   4.2,
        "gnomad_url":       "https://gnomad.broadinstitute.org/short-tandem-repeat/FMR1",
        "in_schema":        0,
        "in_bipex":         0,
        "in_scz_gwas":      0,
        "in_bpd_gwas":      0,
        "in_asd_gwas":      1,
        "evidence_tier":    1,
        "n_studies_tested": 100,
        "n_studies_positive": 100,
        "replication_status": "replicated",
        "phenotypes":       "FXS,ASD,FXTAS,FXPOI",
        "common_name":      "Fragile X CGG repeat",
        "notes":            "Expansion >200 CGG repeats causes methylation-induced silencing of FMR1, leading to Fragile X syndrome (FXS). Premutation range (55-200) causes FXTAS in older males and FXPOI in females. Leading single-gene cause of ASD and inherited intellectual disability.",
    },
    {
        "locus_id":         "chr9:27573528-27573546",
        "chrom":            "chr9",
        "start":            27573528,
        "end":              27573546,
        "motif":            "GGGGCC",
        "motif_length":     6,
        "reference_copies": 2.0,
        "normal_max":       30,
        "pathogenic_min":   400,
        "gene_symbol":      "C9orf72",
        "ensembl_gene_id":  "ENSG00000147894",
        "gene_region":      "intron",
        "tss_distance":     1240,
        "splice_distance":  1240,
        "rexprt_score":     0.96,
        "pli":              0.88,
        "loeuf":            0.31,
        "gnomad_mean_copies": 2.1,
        "gnomad_sd_copies":   0.8,
        "gnomad_url":       "https://gnomad.broadinstitute.org/short-tandem-repeat/C9orf72",
        "in_schema":        0,
        "in_bipex":         0,
        "in_scz_gwas":      0,
        "in_bpd_gwas":      0,
        "in_asd_gwas":      0,
        "evidence_tier":    1,
        "n_studies_tested": 80,
        "n_studies_positive": 80,
        "replication_status": "replicated",
        "phenotypes":       "ALS,FTD",
        "common_name":      "C9orf72 GGGGCC repeat",
        "notes":            "Most common genetic cause of ALS and FTD worldwide. Pathogenic expansions typically >400 repeats. Psychiatric symptoms including psychosis and depression frequently precede motor symptoms. Mechanism involves both toxic RNA foci and dipeptide repeat proteins.",
    },
    {
        "locus_id":         "chr3:63912684-63912714",
        "chrom":            "chr3",
        "start":            63912684,
        "end":              63912714,
        "motif":            "AAGGG",
        "motif_length":     5,
        "reference_copies": 11.0,
        "normal_max":       25,
        "pathogenic_min":   250,
        "gene_symbol":      "RFC1",
        "ensembl_gene_id":  "ENSG00000049541",
        "gene_region":      "intron",
        "tss_distance":     850,
        "splice_distance":  320,
        "rexprt_score":     0.94,
        "pli":              0.91,
        "loeuf":            0.22,
        "gnomad_mean_copies": 11.2,
        "gnomad_sd_copies":   5.8,
        "gnomad_url":       "https://gnomad.broadinstitute.org/short-tandem-repeat/RFC1",
        "in_schema":        0,
        "in_bipex":         0,
        "in_scz_gwas":      0,
        "in_bpd_gwas":      0,
        "in_asd_gwas":      0,
        "evidence_tier":    1,
        "n_studies_tested": 20,
        "n_studies_positive": 20,
        "replication_status": "replicated",
        "phenotypes":       "CANVAS,SCA",
        "common_name":      "RFC1 CANVAS AAGGG repeat",
        "notes":            "Biallelic AAGGG expansion (replacing reference AAAAG) causes CANVAS (cerebellar ataxia, neuropathy, vestibular areflexia syndrome). Multiple pathogenic motifs reported (AAGGG, ACAGG, AGAGG). Recently associated with sensory neuropathy without full CANVAS.",
    },
    {
        "locus_id":         "chr19:45770205-45770264",
        "chrom":            "chr19",
        "start":            45770205,
        "end":              45770264,
        "motif":            "CTG",
        "motif_length":     3,
        "reference_copies": 5.0,
        "normal_max":       34,
        "pathogenic_min":   50,
        "gene_symbol":      "DMPK",
        "ensembl_gene_id":  "ENSG00000104936",
        "gene_region":      "3UTR",
        "tss_distance":     3200,
        "splice_distance":  0,
        "rexprt_score":     0.95,
        "pli":              0.14,
        "loeuf":            0.82,
        "gnomad_mean_copies": 5.2,
        "gnomad_sd_copies":   1.4,
        "gnomad_url":       "https://gnomad.broadinstitute.org/short-tandem-repeat/DMPK",
        "in_schema":        0,
        "in_bipex":         0,
        "in_scz_gwas":      0,
        "in_bpd_gwas":      0,
        "in_asd_gwas":      0,
        "evidence_tier":    1,
        "n_studies_tested": 60,
        "n_studies_positive": 60,
        "replication_status": "replicated",
        "phenotypes":       "DM1",
        "common_name":      "Myotonic dystrophy type 1 CTG repeat",
        "notes":            "CTG expansion in 3'UTR causes myotonic dystrophy type 1 (DM1). Congenital form (>1000 repeats) causes intellectual disability and autism features. Depression and executive dysfunction common in adult-onset. RNA toxic gain-of-function mechanism.",
    },
    {
        "locus_id":         "chr6:16327865-16327940",
        "chrom":            "chr6",
        "start":            16327865,
        "end":              16327940,
        "motif":            "GAA",
        "motif_length":     3,
        "reference_copies": 10.0,
        "normal_max":       33,
        "pathogenic_min":   66,
        "gene_symbol":      "FXN",
        "ensembl_gene_id":  "ENSG00000165060",
        "gene_region":      "intron",
        "tss_distance":     1800,
        "splice_distance":  890,
        "rexprt_score":     0.93,
        "pli":              0.72,
        "loeuf":            0.44,
        "gnomad_mean_copies": 10.8,
        "gnomad_sd_copies":   3.2,
        "gnomad_url":       "https://gnomad.broadinstitute.org/short-tandem-repeat/FXN",
        "in_schema":        0,
        "in_bipex":         0,
        "in_scz_gwas":      0,
        "in_bpd_gwas":      0,
        "in_asd_gwas":      0,
        "evidence_tier":    1,
        "n_studies_tested": 40,
        "n_studies_positive": 40,
        "replication_status": "replicated",
        "phenotypes":       "FRDA",
        "common_name":      "Friedreich ataxia GAA repeat",
        "notes":            "Biallelic GAA expansion in intron 1 causes Friedreich ataxia (FRDA). Epigenetic silencing mechanism via heterochromatin formation. Cardiomyopathy and diabetes frequent. Depression affects ~50% of patients.",
    },
    {
        "locus_id":         "chr6:170561926-170562017",
        "chrom":            "chr6",
        "start":            170561926,
        "end":              170562017,
        "motif":            "CAG",
        "motif_length":     3,
        "reference_copies": 27.0,
        "normal_max":       43,
        "pathogenic_min":   44,
        "gene_symbol":      "ATXN1",
        "ensembl_gene_id":  "ENSG00000124788",
        "gene_region":      "exon",
        "tss_distance":     5200,
        "splice_distance":  0,
        "rexprt_score":     0.95,
        "pli":              0.94,
        "loeuf":            0.18,
        "gnomad_mean_copies": 27.4,
        "gnomad_sd_copies":   3.8,
        "gnomad_url":       "https://gnomad.broadinstitute.org/short-tandem-repeat/ATXN1",
        "in_schema":        0,
        "in_bipex":         0,
        "in_scz_gwas":      0,
        "in_bpd_gwas":      0,
        "in_asd_gwas":      0,
        "evidence_tier":    1,
        "n_studies_tested": 30,
        "n_studies_positive": 30,
        "replication_status": "replicated",
        "phenotypes":       "SCA1",
        "common_name":      "Spinocerebellar ataxia type 1 CAG repeat",
        "notes":            "CAG expansion in ATXN1 causes SCA1. Polyglutamine toxic gain-of-function. Psychiatric symptoms including depression and anxiety common. Cognitive decline in later stages.",
    },
    {
        "locus_id":         "chr12:111598960-111599019",
        "chrom":            "chr12",
        "start":            111598960,
        "end":              111599019,
        "motif":            "CAG",
        "motif_length":     3,
        "reference_copies": 23.0,
        "normal_max":       32,
        "pathogenic_min":   33,
        "gene_symbol":      "ATXN2",
        "ensembl_gene_id":  "ENSG00000204842",
        "gene_region":      "exon",
        "tss_distance":     4100,
        "splice_distance":  0,
        "rexprt_score":     0.94,
        "pli":              0.89,
        "loeuf":            0.24,
        "gnomad_mean_copies": 22.8,
        "gnomad_sd_copies":   2.9,
        "gnomad_url":       "https://gnomad.broadinstitute.org/short-tandem-repeat/ATXN2",
        "in_schema":        0,
        "in_bipex":         0,
        "in_scz_gwas":      0,
        "in_bpd_gwas":      0,
        "in_asd_gwas":      0,
        "evidence_tier":    1,
        "n_studies_tested": 25,
        "n_studies_positive": 25,
        "replication_status": "replicated",
        "phenotypes":       "SCA2,ALS",
        "common_name":      "Spinocerebellar ataxia type 2 CAG repeat",
        "notes":            "CAG expansion causes SCA2. Intermediate alleles (27-32) are a risk factor for ALS via TDP-43 interaction. Psychiatric manifestations common including depression and parkinsonism.",
    },
    {
        "locus_id":         "chr14:92071013-92071119",
        "chrom":            "chr14",
        "start":            92071013,
        "end":              92071119,
        "motif":            "CAG",
        "motif_length":     3,
        "reference_copies": 23.0,
        "normal_max":       35,
        "pathogenic_min":   36,
        "gene_symbol":      "ATXN3",
        "ensembl_gene_id":  "ENSG00000066427",
        "gene_region":      "exon",
        "tss_distance":     8400,
        "splice_distance":  0,
        "rexprt_score":     0.93,
        "pli":              0.77,
        "loeuf":            0.38,
        "gnomad_mean_copies": 23.1,
        "gnomad_sd_copies":   3.2,
        "gnomad_url":       "https://gnomad.broadinstitute.org/short-tandem-repeat/ATXN3",
        "in_schema":        0,
        "in_bipex":         0,
        "in_scz_gwas":      0,
        "in_bpd_gwas":      0,
        "in_asd_gwas":      0,
        "evidence_tier":    1,
        "n_studies_tested": 28,
        "n_studies_positive": 28,
        "replication_status": "replicated",
        "phenotypes":       "SCA3,MJD",
        "common_name":      "Spinocerebellar ataxia type 3 / Machado-Joseph disease",
        "notes":            "Most common SCA worldwide. Polyglutamine expansion in ataxin-3, a deubiquitinating enzyme. Psychiatric features including depression, anxiety, and sleep disorders in majority of patients.",
    },
    {
        "locus_id":         "chr13:70713515-70713560",
        "chrom":            "chr13",
        "start":            70713515,
        "end":              70713560,
        "motif":            "CTG",
        "motif_length":     3,
        "reference_copies": 13.0,
        "normal_max":       34,
        "pathogenic_min":   50,
        "gene_symbol":      "ATXN8OS",
        "ensembl_gene_id":  "ENSG00000230223",
        "gene_region":      "exon",
        "tss_distance":     0,
        "splice_distance":  200,
        "rexprt_score":     0.88,
        "pli":              0.12,
        "loeuf":            1.24,
        "gnomad_mean_copies": 13.4,
        "gnomad_sd_copies":   4.1,
        "gnomad_url":       None,
        "in_schema":        0,
        "in_bipex":         0,
        "in_scz_gwas":      0,
        "in_bpd_gwas":      0,
        "in_asd_gwas":      0,
        "evidence_tier":    1,
        "n_studies_tested": 15,
        "n_studies_positive": 15,
        "replication_status": "replicated",
        "phenotypes":       "SCA8",
        "common_name":      "SCA8 CTG/CAG repeat",
        "notes":            "Bidirectional transcription: CTG expansion on sense strand, CAG on antisense. Both polyglutamine and RNA toxic gain-of-function mechanisms. Psychiatric features including depression and psychosis reported.",
    },
    {
        "locus_id":         "chrX:66765160-66765218",
        "chrom":            "chrX",
        "start":            66765160,
        "end":              66765218,
        "motif":            "CAG",
        "motif_length":     3,
        "reference_copies": 22.0,
        "normal_max":       34,
        "pathogenic_min":   38,
        "gene_symbol":      "AR",
        "ensembl_gene_id":  "ENSG00000169083",
        "gene_region":      "exon",
        "tss_distance":     0,
        "splice_distance":  0,
        "rexprt_score":     0.91,
        "pli":              0.00,
        "loeuf":            1.78,
        "gnomad_mean_copies": 21.8,
        "gnomad_sd_copies":   2.6,
        "gnomad_url":       "https://gnomad.broadinstitute.org/short-tandem-repeat/AR",
        "in_schema":        0,
        "in_bipex":         0,
        "in_scz_gwas":      0,
        "in_bpd_gwas":      0,
        "in_asd_gwas":      0,
        "evidence_tier":    1,
        "n_studies_tested": 20,
        "n_studies_positive": 20,
        "replication_status": "replicated",
        "phenotypes":       "SBMA",
        "common_name":      "Kennedy disease / SBMA CAG repeat",
        "notes":            "X-linked spinobulbar muscular atrophy (Kennedy disease). Polyglutamine expansion in androgen receptor. Depression affects majority of patients. Affects only males due to androgen-dependent toxicity.",
    },
    {
        "locus_id":         "chr22:46191234-46191304",
        "chrom":            "chr22",
        "start":            46191234,
        "end":              46191304,
        "motif":            "ATTCT",
        "motif_length":     5,
        "reference_copies": 10.0,
        "normal_max":       19,
        "pathogenic_min":   800,
        "gene_symbol":      "ATXN10",
        "ensembl_gene_id":  "ENSG00000130638",
        "gene_region":      "intron",
        "tss_distance":     2800,
        "splice_distance":  420,
        "rexprt_score":     0.89,
        "pli":              0.54,
        "loeuf":            0.61,
        "gnomad_mean_copies": 10.2,
        "gnomad_sd_copies":   2.8,
        "gnomad_url":       None,
        "in_schema":        0,
        "in_bipex":         0,
        "in_scz_gwas":      0,
        "in_bpd_gwas":      0,
        "in_asd_gwas":      0,
        "evidence_tier":    1,
        "n_studies_tested": 12,
        "n_studies_positive": 12,
        "replication_status": "replicated",
        "phenotypes":       "SCA10",
        "common_name":      "SCA10 ATTCT repeat",
        "notes":            "Pentanucleotide expansion predominantly in Latin American populations. Seizures in ~50% of cases. RNA toxic gain-of-function mechanism. Depression and cognitive impairment common.",
    },
]

# ── Classical studies ─────────────────────────────────────────
STUDIES = [
    {
        "pmid": "1571412",
        "title": "A novel gene containing a trinucleotide repeat that is expanded and unstable on Huntington's disease chromosomes",
        "first_author": "MacDonald et al.",
        "year": 1993,
        "journal": "Cell",
        "cohort_size_cases": 75,
        "cohort_size_controls": 570,
        "ancestry": "European",
        "sequencing_type": "targeted",
        "tr_calling_tool": "Southern blot / PCR",
        "phenotype": "HD",
        "notes": "Discovery paper for HTT CAG expansion",
    },
    {
        "pmid": "1849664",
        "title": "Identification of a gene (FMR-1) containing a CGG repeat coincident with a breakpoint cluster region exhibiting length variation in fragile X syndrome",
        "first_author": "Verkerk et al.",
        "year": 1991,
        "journal": "Cell",
        "cohort_size_cases": 150,
        "cohort_size_controls": 200,
        "ancestry": "European",
        "sequencing_type": "targeted",
        "tr_calling_tool": "Southern blot",
        "phenotype": "FXS",
        "notes": "Discovery paper for FMR1 CGG expansion",
    },
    {
        "pmid": "21944778",
        "title": "Expanded GGGGCC hexanucleotide repeat in noncoding region of C9ORF72 causes chromosome 9p-linked FTD and ALS",
        "first_author": "DeJesus-Hernandez et al.",
        "year": 2011,
        "journal": "Neuron",
        "cohort_size_cases": 433,
        "cohort_size_controls": 886,
        "ancestry": "European",
        "sequencing_type": "targeted",
        "tr_calling_tool": "Southern blot / repeat-primed PCR",
        "phenotype": "ALS,FTD",
        "notes": "Discovery paper for C9orf72 GGGGCC expansion",
    },
    {
        "pmid": "31427792",
        "title": "Biallelic expansion of an intronic repeat in RFC1 is a common cause of late-onset ataxia",
        "first_author": "Cortese et al.",
        "year": 2019,
        "journal": "Nature Genetics",
        "cohort_size_cases": 220,
        "cohort_size_controls": 448,
        "ancestry": "European",
        "sequencing_type": "WGS",
        "tr_calling_tool": "ExpansionHunter / repeat-primed PCR",
        "phenotype": "CANVAS",
        "notes": "Discovery paper for RFC1 AAGGG expansion in CANVAS",
    },
]

# ── Locus-study evidence links ────────────────────────────────
EVIDENCE = [
    {"locus_id": "chr4:3074876-3074940",   "pmid": "1571412",    "result": "positive", "p_value": 1e-12, "effect_direction": "expansion", "analysis_type": "case-control"},
    {"locus_id": "chrX:147912051-147912110","pmid": "1849664",   "result": "positive", "p_value": 1e-15, "effect_direction": "expansion", "analysis_type": "case-control"},
    {"locus_id": "chr9:27573528-27573546",  "pmid": "21944778",  "result": "positive", "p_value": 1e-8,  "effect_direction": "expansion", "analysis_type": "case-control"},
    {"locus_id": "chr3:63912684-63912714",  "pmid": "31427792",  "result": "positive", "p_value": 1e-9,  "effect_direction": "expansion", "analysis_type": "case-control"},
]


def seed():
    init_db()
    with get_connection() as conn:

        # Insert loci
        n_loci = 0
        for l in LOCI:
            try:
                conn.execute("""
                    INSERT OR IGNORE INTO loci (
                        locus_id, chrom, start, end, motif, motif_length,
                        reference_copies, normal_max, pathogenic_min,
                        gene_symbol, ensembl_gene_id, gene_region,
                        tss_distance, splice_distance, strand,
                        rexprt_score, pli, loeuf,
                        gnomad_mean_copies, gnomad_sd_copies, gnomad_url,
                        in_schema, in_bipex, in_scz_gwas, in_bpd_gwas, in_asd_gwas,
                        evidence_tier, n_studies_tested, n_studies_positive,
                        replication_status, phenotypes, common_name, notes
                    ) VALUES (
                        :locus_id, :chrom, :start, :end, :motif, :motif_length,
                        :reference_copies, :normal_max, :pathogenic_min,
                        :gene_symbol, :ensembl_gene_id, :gene_region,
                        :tss_distance, :splice_distance, '+',
                        :rexprt_score, :pli, :loeuf,
                        :gnomad_mean_copies, :gnomad_sd_copies, :gnomad_url,
                        :in_schema, :in_bipex, :in_scz_gwas, :in_bpd_gwas, :in_asd_gwas,
                        :evidence_tier, :n_studies_tested, :n_studies_positive,
                        :replication_status, :phenotypes, :common_name, :notes
                    )
                """, l)
                n_loci += 1
            except Exception as e:
                print(f"  ⚠ Locus {l['locus_id']}: {e}")

        # Insert studies
        n_studies = 0
        pmid_to_id = {}
        for s in STUDIES:
            try:
                cur = conn.execute("""
                    INSERT OR IGNORE INTO studies (
                        pmid, title, first_author, year, journal,
                        cohort_size_cases, cohort_size_controls,
                        ancestry, sequencing_type, tr_calling_tool,
                        phenotype, notes
                    ) VALUES (
                        :pmid, :title, :first_author, :year, :journal,
                        :cohort_size_cases, :cohort_size_controls,
                        :ancestry, :sequencing_type, :tr_calling_tool,
                        :phenotype, :notes
                    )
                """, s)
                if cur.lastrowid:
                    pmid_to_id[s["pmid"]] = cur.lastrowid
                    n_studies += 1
            except Exception as e:
                print(f"  ⚠ Study {s['pmid']}: {e}")

        # Fetch all study IDs by PMID
        rows = conn.execute("SELECT id, pmid FROM studies").fetchall()
        for row in rows:
            pmid_to_id[row["pmid"]] = row["id"]

        # Insert evidence links
        n_ev = 0
        for ev in EVIDENCE:
            study_id = pmid_to_id.get(ev["pmid"])
            if not study_id:
                continue
            try:
                conn.execute("""
                    INSERT OR IGNORE INTO locus_evidence (
                        locus_id, study_id, result, p_value,
                        effect_direction, analysis_type
                    ) VALUES (?, ?, ?, ?, ?, ?)
                """, (ev["locus_id"], study_id, ev["result"],
                      ev["p_value"], ev["effect_direction"], ev["analysis_type"]))
                n_ev += 1
            except Exception as e:
                print(f"  ⚠ Evidence {ev['locus_id']}: {e}")

        # Update DB meta counts
        total_loci    = conn.execute("SELECT COUNT(*) FROM loci").fetchone()[0]
        total_studies = conn.execute("SELECT COUNT(*) FROM studies").fetchone()[0]
        conn.execute("UPDATE db_meta SET value=? WHERE key='n_loci'",    (str(total_loci),))
        conn.execute("UPDATE db_meta SET value=? WHERE key='n_studies'", (str(total_studies),))

    print(f"\n✅ Seeding complete")
    print(f"   {n_loci} loci inserted")
    print(f"   {n_studies} studies inserted")
    print(f"   {n_ev} evidence links inserted")
    print(f"   Database now has {total_loci} total loci, {total_studies} total studies")


if __name__ == "__main__":
    seed()
